# SITE CONFIGURATION
title: tl;dnr # your site title
author: Sebastian Glahn # You :P
description: > # Meta description of Homepage
    The personal Blog of Sebastian Glahn
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.tldnr.org" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sebastian Glahn
  links:
    - https://twitter.com/sglahn
    - https://github.com/sglahn

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Archive', link: '/archives'}

tagline: >
    Sebastian Glahn's Playground

hero_img: posts/hero_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

twitter_username: sglahn # replace with your_twitter_username or comment to remove link from footer
github_username:  sglahn # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: blog-tldnr-org # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:year/:month/:day/:title/
#paginate_path: /posts/:num/
#paginate: 5

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-analytics
#  - jekyll-archives
#  - jekyll-paginate
     
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-119131230-1      # Required - replace with your tracking id
    
#jekyll-archives:
#  enabled:
#    - categories
#  layout: category_archives
#  permalinks:
#    category: /categories/:name/

